# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "chef/centos-7.0"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end
  config.vm.synced_folder "../../../../", "/vagrant"
  config.vm.provision :shell, :path => "./bootstrap.sh"
  config.vbguest.auto_update = false
end
