# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "384"]
  end
  config.vm.synced_folder "../../../../", "/vagrant"
  config.vm.provision :shell, :path => "./bootstrap.sh"
end
