ARG TARGET
ARG PKGR_VERSION
FROM barebuild/$TARGET
WORKDIR /app

RUN curl -GLs https://buildcurl.com -d recipe=pkgr -d version="$PKGR_VERSION" -d target="$TARGET" -o - | tar xzf - -C /usr/local
ENTRYPOINT ["/usr/local/bin/pkgr", "package", ".", "--clean", "--auto", "--compile-cache-dir", "/cache"]
