#!/bin/bash
set -e
set -o pipefail

build_docker_image() {
	file=$1
	osversiondir=$(dirname $file)
	osfamilydir=$(dirname $osversiondir)
	osversion=$(basename $osversiondir)
	osfamily=$(basename $osfamilydir)
	target="$osfamily:$osversion"
	docker_tag="$DOCKER_ORG/$osfamily:$osversion"

	echo $docker_tag
	docker build --pull --build-arg PKGR_VERSION -t $docker_tag $osversiondir
}

build_docker_image "$1"
